version: "2.1"
services:
  centers-ms:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      centers-db:
        condition: service_healthy
    healthcheck:
      test: "curl -I centers-ms:3000/centers-ms/resources/centers/ --fail"
      interval: 20s
      retries: 10
  centers-db:
    image: mysql:5.7
    healthcheck:
      test: "mysqlcheck -u$$MYSQL_USER -p$$MYSQL_PASSWORD $$MYSQL_DATABASE"
      interval: 20s
      timeout: 5s
      retries: 15
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: centers-db
      MYSQL_USER: sa
      MYSQL_PASSWORD: 123
    ports:
      - "3306:3306"
